apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mgdb
  name: mgdb
  namespace: biz
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
    release: mongodb
status:
  loadBalancer: {}
