apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qa
  name: qa
  namespace: biz
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "81"
    port: 81
    targetPort: 80
  selector:
    io.kompose.service: qa
status:
  loadBalancer: {}