apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qaclickhouse
  name: qaclickhouse
  namespace: biz
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "8123"
    port: 8123
    targetPort: 8123
  - name: "9009"
    port: 9009
    targetPort: 9009
  selector:
    io.kompose.service: qaclickhouse
status:
  loadBalancer: {}
