apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: qaclickhouse
  name: qaclickhouse
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: qaclickhouse
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        image: daocloud.io/quantaxis/qa-clickhouse
        name: qaclickhouse
        ports:
        - containerPort: 9000
        - containerPort: 8123
        - containerPort: 9009
        resources: {}
      restartPolicy: Always
status: {}
