apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qacode
  namespace: biz
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "worker03-nfs-client"
