apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: qactpbeebroker
  name: qactpbeebroker
  namespace: biz
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: qactpbeebroker
    spec:
      containers:
      - args:
        - /root/wait_for_it.sh
        - qaeventmq:15672
        - --
        - QACTPBEE
        - --userid
        - "133496"
        - --password
        - QCHL1234
        image: daocloud.io/quantaxis/qactpbeebroker:latest
        name: qactpbeebroker
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
