apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qamarketcollector
  name: qamarketcollector
  namespace: biz
spec:
  ports:
  - name: "8011"
    port: 8011
    targetPort: 8011
  selector:
    io.kompose.service: qamarketcollector
status:
  loadBalancer: {}
