apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: qamarketcollector
  name: qamarketcollector
  namespace: biz
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: qamarketcollector
    spec:
      containers:
      - args:
        - /root/QUANTAXIS_RealtimeCollector/docker/wait_for_it.sh
        - qaeventmq:5672
        - --
        - /root/QUANTAXIS_RealtimeCollector/docker/start_collector.sh
        env:
        - name: EventMQ_IP
          value: qaeventmq
        - name: MONGODB
          value: mgdb
        image: daocloud.io/quantaxis/qarealtimecollector:latest
        name: qamarketcollector
        ports:
        - containerPort: 8011
        resources: {}
      #   volumeMounts:
      #   - mountPath: /home
      #     name: qacode
      # volumes:
      # - name: qacode
      #   persistentVolumeClaim:
      #     claimName: qacode
      restartPolicy: Always
status: {}
