apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: qamonitor
  name: qamonitor
  namespace: biz
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: qamonitor
    spec:
      containers:
      - image: daocloud.io/quantaxis/qa-monitor:latest
        name: qamonitor
        ports:
        - containerPort: 61209
        - containerPort: 61208
        resources: {}
      hostPID: true
      restartPolicy: Always
      securityContext: {}
status: {}
