apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qamonitor
  name: qamonitor
  namespace: biz
spec:
  ports:
  - name: "61209"
    port: 61209
    targetPort: 61209
  - name: "61208"
    port: 61208
    targetPort: 61208
  selector:
    io.kompose.service: qamonitor
status:
  loadBalancer: {}
