apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qaredis
  name: qaredis
  namespace: biz
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: qaredis
status:
  loadBalancer: {}
