apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: qatrader
  name: qatrader
spec:
  ports:
  - name: "8020"
    port: 8020
    targetPort: 8020
  selector:
    io.kompose.service: qatrader
status:
  loadBalancer: {}
