apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: qatrader
  name: qatrader
  namespace: biz
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: qatrader
    spec:
      containers:
      - args:
        - /root/QATrader/docker/wait_for_it.sh
        - qaeventmq:5672
        - --
        - qatraderserver
        env:
        - name: MONGODB
          value: mgdb
        - name: QAPUBSUB_IP
          value: qaeventmq
        - name: QAPUBSUB_PORT
          value: "5672"
        - name: QAPUBSUB_PWD
          value: admin
        - name: QAPUBSUB_USER
          value: admin
        - name: QARUN_AMQP
          value: pyamqp://admin:admin@qaeventmq:5672//
        - name: TZ
          value: Asia/Shanghai
        image: daocloud.io/quantaxis/qatrader:latest
        name: qatrader
        ports:
        - containerPort: 8020
        resources: {}
      restartPolicy: Always
status: {}
