apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qatrader
  name: qatrader
  namespace: biz
spec:
  ports:
  - name: "8020"
    port: 8020
    targetPort: 8020
  selector:
    io.kompose.service: qatrader
status:
  loadBalancer: {}
