apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qaeditor
  name: qaeditor
  namespace: biz
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3000
  selector:
    io.kompose.service: qaeditor
status:
  loadBalancer: {}