apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qaweb-run
  name: qaweb-run
  namespace: biz
spec:
  ports:
  - name: "8010"
    port: 8010
    targetPort: 8010
  selector:
    io.kompose.service: qaweb-run
status:
  loadBalancer: {}
