apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
      - args:
        - scheduler
        env:
        - name: EXECUTOR
          value: Celery
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: LOAD_EX
          value: "n"
        image: puckel/docker-airflow
        name: scheduler
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: qadag
      restartPolicy: Always
      volumes:
      - name: qadag
        persistentVolumeClaim:
          claimName: qadag
status: {}
